config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, :description, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_attributes)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_attributes
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our Flats (<%= @flats.length %>)</h1>

<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="flat">
          <div class="flat-content">
            <h2><%= flat.name %></h2>
            <p><%= flat.address %></p>
            <div class="flat-numbers">
             <i class="fas fa-users"><%= flat.number_of_guests %></i>
              <i class="fas fa-euro-sign"><%= flat.price_per_night %></i>
            </div>
          </div>
          <div class="flat-links">
            <%= link_to "More info", flat_path(flat.id)%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name, class: "form-control" %>
  <%= f.input :address, class: "form-control" %>
  <%= f.input :description, class: "form-control" %>
  <%= f.input :price_per_night, class: "form-control" %>
  <%= f.input :number_of_guests, class: "form-control" %>
  <%= f.input :lon, class: "form-control" %>
  <%= f.input :lat, class: "form-control" %>
  <%= f.submit "Create flat", class: "btn btn-primary"%>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<h2>A bit more about this flat...</h2>
<p><%= @flat.description %></p>

<p><%= link_to "go back to list", flats_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="title">
        Simple AirBnB
      </div>
      <div class="add-flat btn btn-outline-primary">
        <%= link_to "Add flat", new_flat_path %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>